package com.example.ismapc

import android.util.Log
import com.google.ai.client.generativeai.GenerativeModel
import com.google.ai.client.generativeai.type.content
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.Timestamp
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.coroutines.tasks.await
import java.util.*

/**
 * Service to interact with Gemini AI for generating content suggestions
 * based on a child's app usage patterns.
 */
class GeminiContentService {
    private val TAG = "GeminiContentService"
    private val firestore = FirebaseFirestore.getInstance()
    private val auth = FirebaseAuth.getInstance()
    
    // Replace with your actual API key from Google AI Studio
    private val API_KEY = "AIzaSyDkTwtjy5PdrlNfk3mE2n24s1Dk2Y5XWGU" 
    
    // Categories for suggestions
    enum class SuggestionCategory {
        EDUCATIONAL, ENTERTAINMENT, PRODUCTIVITY, HEALTH, CREATIVE
    }
    
    // Data class for structured suggestions
    data class ContentSuggestion(
        val title: String,
        val description: String,
        val category: SuggestionCategory,
        val ageAppropriate: Boolean = true,
        val imageUrl: String? = null,
        val linkUrl: String? = null,
        val timestamp: Long = Calendar.getInstance().timeInMillis
    )
    
    /**
     * Generate content suggestions based on the child's app usage data.
     * @param childId The ID of the child to generate suggestions for
     * @return List of content suggestions or empty list if generation fails
     */
    suspend fun generateSuggestions(childId: String): List<ContentSuggestion> {
        try {
            Log.d(TAG, "Generating suggestions for child: $childId")
            
            // 1. Retrieve the child's app usage data from Firestore
            val appUsageData = getAppUsageData(childId)
            if (appUsageData.isEmpty()) {
                Log.e(TAG, "No app usage data available for child: $childId. Using fallback suggestions.")
                return generateFallbackSuggestions()
            }
            
            // 2. Get child's profile to know their age
            val childAge = getChildAge(childId)
            Log.d(TAG, "Child age: $childAge")
            
            // 3. Format data for Gemini prompt
            val prompt = createGeminiPrompt(appUsageData, childAge)
            Log.d(TAG, "Generated prompt: $prompt")
            
            // 4. Call Gemini API
            val suggestions = callGeminiAPI(prompt)
            if (suggestions.isEmpty()) {
                Log.w(TAG, "No suggestions generated by Gemini. Using fallback suggestions.")
                return generateFallbackSuggestions()
            }
            
            return suggestions
        } catch (e: Exception) {
            Log.e(TAG, "Error generating suggestions: ${e.message}", e)
            return generateFallbackSuggestions()
        }
    }
    
    /**
     * Retrieve the child's app usage data from Firestore.
     */
    private suspend fun getAppUsageData(childId: String): Map<String, Long> {
        return try {
            val result = mutableMapOf<String, Long>()
            
            val document = withContext(Dispatchers.IO) {
                firestore.collection("appUsage")
                    .document(childId)
                    .collection("stats")
                    .document("daily")
                    .get()
                    .await()
            }
            
            if (document.exists()) {
                Log.d(TAG, "Found app usage data for child: $childId")
                @Suppress("UNCHECKED_CAST")
                val appsData = document.get("apps") as? Map<String, Map<String, Any>> ?: return emptyMap()
                
                for ((appName, appData) in appsData) {
                    val weeklyMinutes = (appData["weeklyMinutes"] as? Number)?.toLong() ?: 0L
                    val packageName = (appData["packageName"] as? String) ?: ""
                    
                    // Skip sample data
                    if (packageName.contains(".SAMPLE") || appName.contains("[SAMPLE]")) {
                        Log.d(TAG, "Skipping sample app: $appName")
                        continue
                    }
                    
                    // Store app usage time
                    result[appName] = weeklyMinutes
                    Log.d(TAG, "Added app usage: $appName - $weeklyMinutes minutes")
                }
            } else {
                Log.w(TAG, "No app usage data found for child: $childId")
            }
            
            result
        } catch (e: Exception) {
            Log.e(TAG, "Error retrieving app usage data: ${e.message}", e)
            emptyMap()
        }
    }
    
    /**
     * Get child's age from their profile.
     */
    private suspend fun getChildAge(childId: String): Int {
        return try {
            val document = withContext(Dispatchers.IO) {
                firestore.collection("users")
                    .document("child")
                    .collection("profile")
                    .document(childId)
                    .get()
                    .await()
            }
            
            if (document.exists()) {
                Log.d(TAG, "Found child profile document for: $childId")
                val birthDateTimestamp = document.get("birthDate") as? Timestamp
                val birthDate = birthDateTimestamp?.toDate()
                if (birthDate != null) {
                    val calendar = Calendar.getInstance()
                    val currentYear = calendar.get(Calendar.YEAR)
                    calendar.time = birthDate
                    val birthYear = calendar.get(Calendar.YEAR)
                    val age = currentYear - birthYear
                    Log.d(TAG, "Calculated age: $age for child: $childId")
                    return age
                }
            } else {
                Log.w(TAG, "No profile document found for child: $childId")
            }
            
            // Default age if not found
            val defaultAge = 10
            Log.w(TAG, "Using default age ($defaultAge) for child: $childId")
            defaultAge
        } catch (e: Exception) {
            Log.e(TAG, "Error getting child age: ${e.message}", e)
            val fallbackAge = 10
            Log.w(TAG, "Using fallback age ($fallbackAge) for child: $childId")
            fallbackAge
        }
    }
    
    /**
     * Create a structured prompt for Gemini based on the child's app usage and age.
     */
    private fun createGeminiPrompt(appUsage: Map<String, Long>, childAge: Int): String {
        // Sort apps by usage time (descending)
        val sortedApps = appUsage.entries.sortedByDescending { it.value }
            .take(10)
        
        // Analyze usage patterns
        val totalUsage = appUsage.values.sum()
        val educationalApps = sortedApps.filter { it.key.contains("edu") || it.key.contains("learn") }
        val entertainmentApps = sortedApps.filter { it.key.contains("game") || it.key.contains("play") }
        val productivityApps = sortedApps.filter { it.key.contains("note") || it.key.contains("todo") }
        
        val educationalTime = educationalApps.sumOf { it.value }
        val entertainmentTime = entertainmentApps.sumOf { it.value }
        val productivityTime = productivityApps.sumOf { it.value }
        
        val usagePatterns = buildString {
            append("Usage Patterns:\n")
            append("- Educational usage: ${"%.1f".format(100.0 * educationalTime / totalUsage)}%\n")
            append("- Entertainment usage: ${"%.1f".format(100.0 * entertainmentTime / totalUsage)}%\n")
            append("- Productivity usage: ${"%.1f".format(100.0 * productivityTime / totalUsage)}%\n")
        }
        
        val appListText = sortedApps.joinToString("\n") { (app, minutes) ->
            "- $app: ${minutes} minutes per week"
        }
        
        Log.d(TAG, "Usage patterns analysis:")
        Log.d(TAG, usagePatterns)
        Log.d(TAG, "Top apps:")
        sortedApps.forEach { (app, minutes) ->
            Log.d(TAG, "App: $app, Usage: $minutes minutes")
        }
        
        return """
            You are a helpful assistant providing content suggestions for a child.
            
            Child's age: $childAge years old
            Usage Patterns: $usagePatterns
            
            The child frequently uses these apps (weekly usage time):
            $appListText
            
            Based on this information and usage patterns, suggest 5 age-appropriate content ideas, activities, or resources that:
            1. Align with the child's interests shown by their app usage
            2. Are educational but engaging
            3. Are appropriate for a $childAge-year-old child
            4. Encourage healthy digital habits
            5. Include a mix of online and offline activities
            6. Consider the usage patterns (educational vs entertainment vs productivity)
            
            Format each suggestion as follows:
            Title: [Title]
            Description: [Brief description]
            Category: [One of: EDUCATIONAL, ENTERTAINMENT, PRODUCTIVITY, HEALTH, CREATIVE]
            ImageURL: [Optional URL to a relevant image]
            LinkURL: [Optional URL to a website, video, or resource]
            
            IMPORTANT: 
            - Ensure all suggestions are age-appropriate, safe, and beneficial for a $childAge-year-old child.
            - For online suggestions, include direct URLs to safe, child-appropriate resources.
            - For image suggestions, provide URLs to appropriate educational or informative images.
            - All URLs must be to reputable, safe, and age-appropriate websites.
            - Consider the usage patterns and suggest a balanced mix of educational and entertainment content
        """.trimIndent()
    }
    
    /**
     * Call the Gemini API to generate suggestions.
     */
    private suspend fun callGeminiAPI(prompt: String): List<ContentSuggestion> {
        return try {
            Log.d(TAG, "Calling Gemini API with prompt: $prompt")
            
            // Initialize Gemini model
            val model = GenerativeModel(
                modelName = "gemini-pro",
                apiKey = API_KEY
            )
            
            // Generate content
            val response = withContext(Dispatchers.IO) {
                model.generateContent(
                    content {
                        text(prompt)
                    }
                )
            }
            
            val responseText = response.text ?: ""
            Log.d(TAG, "Gemini response received: $responseText")
            
            // Parse the response into structured suggestion objects
            parseGeminiResponse(responseText)
        } catch (e: Exception) {
            Log.e(TAG, "Error calling Gemini API: ${e.message}", e)
            
            // Return fallback suggestions in case of API failure
            generateFallbackSuggestions()
        }
    }
    
    /**
     * Parse the Gemini text response into structured ContentSuggestion objects.
     */
    private fun parseGeminiResponse(response: String): List<ContentSuggestion> {
        val suggestions = mutableListOf<ContentSuggestion>()
        
        try {
            // Split the response by suggestion blocks (each starting with "Title:")
            val suggestionBlocks = response.split("Title:").filter { it.isNotBlank() }
            
            for (block in suggestionBlocks) {
                try {
                    val lines = block.trim().split("\n")
                    
                    val title = lines[0].trim()
                    
                    // Find description line
                    val descriptionLine = lines.find { it.startsWith("Description:") }
                    val description = descriptionLine?.substringAfter("Description:")?.trim() ?: ""
                    
                    // Find category line
                    val categoryLine = lines.find { it.startsWith("Category:") }
                    val categoryStr = categoryLine?.substringAfter("Category:")?.trim() ?: "EDUCATIONAL"
                    
                    // Parse category
                    val category = try {
                        SuggestionCategory.valueOf(categoryStr.uppercase())
                    } catch (e: Exception) {
                        SuggestionCategory.EDUCATIONAL
                    }
                    
                    // Find image URL
                    val imageUrlLine = lines.find { it.startsWith("ImageURL:") }
                    val imageUrl = imageUrlLine?.substringAfter("ImageURL:")?.trim()
                    
                    // Find link URL
                    val linkUrlLine = lines.find { it.startsWith("LinkURL:") }
                    val linkUrl = linkUrlLine?.substringAfter("LinkURL:")?.trim()
                    
                    // Create and add suggestion
                    suggestions.add(
                        ContentSuggestion(
                            title = title,
                            description = description,
                            category = category,
                            imageUrl = imageUrl,
                            linkUrl = linkUrl
                        )
                    )
                } catch (e: Exception) {
                    Log.e(TAG, "Error parsing suggestion block: $block", e)
                    // Continue with next block
                }
            }
        } catch (e: Exception) {
            Log.e(TAG, "Error parsing Gemini response: ${e.message}", e)
        }
        
        return if (suggestions.isEmpty()) {
            // If parsing failed, return fallback suggestions
            generateFallbackSuggestions()
        } else {
            suggestions
        }
    }
    
    /**
     * Generate fallback suggestions in case the API call fails.
     */
    private fun generateFallbackSuggestions(): List<ContentSuggestion> {
        return listOf(
            // Educational Suggestions
            ContentSuggestion(
                title = "Science Experiment",
                description = "Create a homemade volcano using baking soda and vinegar. Learn about chemical reactions!",
                category = SuggestionCategory.EDUCATIONAL,
                imageUrl = "https://cdn-icons-png.flaticon.com/512/2172/2172493.png",
                linkUrl = "https://www.sciencekids.co.nz/experiments/volcano.html"
            ),
            ContentSuggestion(
                title = "Math Games",
                description = "Play free math games that make learning fun and interactive.",
                category = SuggestionCategory.EDUCATIONAL,
                imageUrl = "https://cdn-icons-png.flaticon.com/512/2331/2331860.png",
                linkUrl = "https://www.mathplayground.com/"
            ),
            ContentSuggestion(
                title = "Story Time",
                description = "Listen to free audiobooks from LibriVox while you draw or color.",
                category = SuggestionCategory.EDUCATIONAL,
                imageUrl = "https://cdn-icons-png.flaticon.com/512/2436/2436882.png",
                linkUrl = "https://librivox.org/"
            ),

            // Creative Suggestions
            ContentSuggestion(
                title = "DIY Craft",
                description = "Create a paper plate mask using markers, glue, and string.",
                category = SuggestionCategory.CREATIVE,
                imageUrl = "https://cdn-icons-png.flaticon.com/512/1547/1547527.png",
                linkUrl = "https://www.redtedart.com/"
            ),
            ContentSuggestion(
                title = "Music Exploration",
                description = "Experiment with different sounds using free online instruments.",
                category = SuggestionCategory.CREATIVE,
                imageUrl = "https://cdn-icons-png.flaticon.com/512/2721/2721620.png",
                linkUrl = "https://www.musiclab.chromeexperiments.com/"
            ),
            ContentSuggestion(
                title = "Draw and Write",
                description = "Create a comic strip about your day or a story you imagine.",
                category = SuggestionCategory.CREATIVE,
                imageUrl = "https://cdn-icons-png.flaticon.com/512/1547/1547527.png",
                linkUrl = "https://www.drawspace.com/"
            ),

            // Health and Outdoor Suggestions
            ContentSuggestion(
                title = "Family Yoga",
                description = "Try some simple yoga poses together with your family.",
                category = SuggestionCategory.HEALTH,
                imageUrl = "https://cdn-icons-png.flaticon.com/512/2382/2382461.png",
                linkUrl = "https://www.yogawithadriene.com/"
            ),
            ContentSuggestion(
                title = "Garden Project",
                description = "Start a small garden with easy-to-grow plants like beans or sunflowers.",
                category = SuggestionCategory.HEALTH,
                imageUrl = "https://cdn-icons-png.flaticon.com/512/2382/2382461.png",
                linkUrl = "https://www.kidsgardening.org/"
            ),
            ContentSuggestion(
                title = "Dance Party",
                description = "Create a playlist of your favorite songs and have a dance party!",
                category = SuggestionCategory.HEALTH,
                imageUrl = "https://cdn-icons-png.flaticon.com/512/2721/2721620.png",
                linkUrl = "https://www.go noodle.com/"
            ),

            // Productivity Suggestions
            ContentSuggestion(
                title = "Mind Map",
                description = "Create a mind map of your interests and goals using paper and markers.",
                category = SuggestionCategory.PRODUCTIVITY,
                imageUrl = "https://cdn-icons-png.flaticon.com/512/2721/2721620.png",
                linkUrl = "https://www.mindmeister.com/"
            ),
            ContentSuggestion(
                title = "Journaling",
                description = "Write about your day, your feelings, or your dreams.",
                category = SuggestionCategory.PRODUCTIVITY,
                imageUrl = "https://cdn-icons-png.flaticon.com/512/2436/2436882.png",
                linkUrl = "https://www.journalbuddies.com/"
            ),
            ContentSuggestion(
                title = "Coding Challenge",
                description = "Build a simple game using Scratch blocks.",
                category = SuggestionCategory.PRODUCTIVITY,
                imageUrl = "https://cdn-icons-png.flaticon.com/512/2721/2721620.png",
                linkUrl = "https://scratch.mit.edu/"
            )
        )
    }
    
    /**
     * Store the generated suggestions in Firestore.
     */
    // Removed since we're not storing suggestions in Firestore anymore
} 